apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Yasminemaroukk/appOfApps
    targetRevision: HEAD
    path: appOfApps/manifests 
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated: 
      prune: true 
      selfHeal: true 
  
