apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/Yasminemaroukk/appOfApps
    targetRevision: HEAD
    path: ./app-of-apps/manifests
   
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd

  
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated: 
      prune: true 
      selfHeal: true 
  
