apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:

  project: default

  source:
    repoURL: https://github.com/codefresh-contrib/gitops-cert-level-2-examples.git
    targetRevision: HEAD
    path: my-app-list
   
    directory:
      recurse: false
 
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 
      allowEmpty: false 
